<a href="https://colab.research.google.com/github/sanho-is-coral/colab_practice/blob/main/Colaboratory%EC%97%90_%EC%98%A4%EC%8B%A0_%EA%B2%83%EC%9D%84_%ED%99%98%EC%98%81%ED%95%A9%EB%8B%88%EB%8B%A4%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
#Iris
import tensorflow as tf
import pandas as pd

fileRoute='https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris=pd.read_csv(fileRoute)
encoding=pd.get_dummies(iris)#원핫인코딩을 위한 데이터 준비. 종속값이 범주형 데이터일 때 범주를 칼럼 형태로 만듬

x=encoding[['꽃잎길이','꽃잎폭','꽃받침길이','꽃받침폭']]
y=encoding[['품종_setosa','품종_versicolor','품종_virginica']]

X=tf.keras.layers.Input(shape=[4])
Y=tf.keras.layers.Dense(3, activation='softmax')(X) #softmax는 결과값을 확률지표로 보여줌
model=tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy',metrics='accuracy') 
#회귀는 mse 분류는 crossentropy 사용, accuracy는 결과창에서 정확도 출력
model.fit(x,y,epochs=1000, verbose=0)
print(model.predict(x[-5:]))

[[1.1568188e-06 1.3497676e-01 8.6502212e-01]
 [2.6568596e-06 2.4322969e-01 7.5676763e-01]
 [4.2326615e-06 2.3043914e-01 7.6955658e-01]
 [7.9137237e-07 6.5322042e-02 9.3467718e-01]
 [8.2609758e-06 2.2185893e-01 7.7813280e-01]]
